source:
  type: airflow
  config:
    connection:
      conn_type: sqlite
      host: "/opt/airflow/airflow.db"
    dag_filter_pattern:
      allow:
        - ".*"
    capture_ownership_info: true
    capture_tags_info: true
    include_lineage: true
    openlineage_endpoint: "http://datahub-gms:8080/openapi/openlineage/"

sink:
  type: datahub-rest
  config:
    server: "http://datahub-gms:8080"

pipeline_name: "melisimlake_airflow"
