version: 2

sources:
  - name: silver
    schema: silver
    tables:
      - name: users
        description: "Usuários Silver com SCD Type 2"
        columns:
          - name: user_id
            tests: [not_null]
          - name: email
            tests: [not_null]
          - name: is_current
            tests: [not_null]

      - name: products
        description: "Produtos Silver com SCD Type 2"
        columns:
          - name: product_id
            tests: [not_null]

      - name: orders
        description: "Pedidos Silver"
        columns:
          - name: order_id
            tests: [not_null, unique]

      - name: events
        description: "Eventos comportamentais Silver"
        columns:
          - name: event_id
            tests: [not_null, unique]
